# Generated by Django 3.2.5 on 2021-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_regression', '0002_auto_20210711_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradientdescent',
            old_name='pub_date',
            new_name='last_edited',
        ),
        migrations.AddField(
            model_name='gradientdescent',
            name='num_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gradientdescent',
            name='points_ready',
            field=models.BooleanField(default=False),
        ),
    ]
