# Generated by Django 3.2.5 on 2021-07-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_regression', '0003_auto_20210712_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradientdescent',
            name='current_step',
            field=models.IntegerField(default=0),
        ),
    ]
